### ISSUE TITLE
Problemas no codigo

### ISSUE THREAD

**Issue by BielLelis** [Azganoth/nike-bot#1]
O primeiro é que na linha 32 tem os 2 sinais ?? "const page = (await browser.pages())[0] ?? (await browser.newPage());" que consegui resolver trocando por const page = (await browser.pages) mas logo em seguida recebo esse erro "TypeError: page.setRequestInterception is not a function" que ainda não descobrir como arrumar.

**Comment by Azganoth** [comment]
Os dois sinals (`??`) não são um problema, eles fazem com que a expressão à direita seja executada caso a expressão à esquerda retorne `null` ou `undefined` ([explicação mais detalhada](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Operators/operador_de_coalescencia_nula)).
