### ISSUE TITLE
Rodar

### ISSUE THREAD

**Issue by jsouza678** [Azganoth/nike-bot#2]
Olá, tudo bem?

Gostei bastante do código... tem alguma previsão de ficar pronto? Só por curiosidade mesmo

**Comment by Azganoth** [comment]
Ainda falta realizar testes de estresse, e eles só podem ser realizados quando houver lançamento de produtos muito procurados, então pode demorar um pouco para ficar pronto.

**Comment by jsouza678** [comment]
Legal, entendi.. ontem rodei aqui e tá dando certo, só tive que alterar o timeout para 3.000
O pior é que tem gente que tem bots que compram com 3 segundos.. é quase impossível

**Comment by jsouza678** [comment]
Seria legal também se vc aceitar sugestão, o preenchimento do cartão (se n tiver salvo)

**Comment by Azganoth** [comment]
Essa feature está planejada pra ser implementada, mas a prioridade agora é ter certeza que esse bot execute uma compra rápido, com o mínimo de configuração e "ações" possíveis.
