### ISSUE TITLE
Tempo

### ISSUE THREAD

**Issue by ThayaneQuintanilha** [Azganoth/nike-bot#4]
Amigo, terá muitos lançamentos para este mês e mês que vem, irá continuar com os testes? E em quanto tempo a compra ta sendo realizada com o sms?

**Comment by Azganoth** [comment]
Estou com pouco tempo livre pra desenvolver esse projeto, provavelmente não estará pronto pro mês que vem. As compras com SMS não estão funcionando no momento.
